### ISSUE TITLE
Error after updating to Papermc 265 for 1.16.4

### ISSUE THREAD

**Issue by Freddo3000** [RoinujNosde/Dynmap-SimpleClans#11]
/plugins output

```
[14:03:38 INFO]: Plugins (20): BetterSleeping3, BigDoors, BKCommonLib, Brewery, Cannons, Chairs, DiscordSRV, dynmap*, Dynmap-SimpleClans*, FastLeafDecay, LockettePro, LogBlock, ProtocolLib, Ships, Shopkeepers, SimpleClans, TCHangRail, Train_Carts, WorldBorder, WorldEdit
```

Relevant log:
```
[14:01:07] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-beta4-421*
[14:01:07] [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)
[14:01:07] [Server thread/INFO]: [SimpleClans] Enabling SimpleClans v2.14.3
[14:01:07] [Server thread/INFO]: [SimpleClans] Vault not found. No economy or extended Permissions support.
[14:01:07] [Server thread/INFO]: [SimpleClans] MySQL Connection successful
[14:01:07] [Server thread/INFO]: [SimpleClans] Clans: 2
[14:01:07] [Server thread/INFO]: [SimpleClans] Clan players: 5
[14:01:07] [Thread-15/INFO]: [BetterSleeping3] You are using the latest version: 3.0.4
[14:01:07] [Server thread/INFO]: [SimpleClans] [ACF] Enabled Asynchronous Tab Completion Support!
[14:01:07] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 39 ms to scan 1 urls, producing 5 keys and 7 values 
[14:01:07] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 14 ms to scan 1 urls, producing 27 keys and 92 values 
[14:01:08] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 3 ms to scan 1 urls, producing 6 keys and 25 values 
[14:01:08] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 3 ms to scan 1 urls, producing 6 keys and 18 values 
[14:01:08] [Server thread/INFO]: [SimpleClans] Multithreading: true
[14:01:08] [Server thread/INFO]: [SimpleClans] BungeeCord: false
[14:01:08] [Server thread/INFO]: [SimpleClans] Help us translate SimpleClans to your language! Access https://crowdin.com/project/simpleclans/
[14:01:08] [Server thread/INFO]: [Dynmap-SimpleClans] Enabling Dynmap-SimpleClans v1.4.0*
[14:01:08] [Server thread/INFO]: [Dynmap-SimpleClans] initializing
[14:01:08] [Server thread/ERROR]: Error occurred while enabling Dynmap-SimpleClans v1.4.0 (Is it up to date?)
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:1042) ~[?:?]
	at net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans.initApis(DynmapSimpleClans.java:122) ~[?:?]
	at net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans.activate(DynmapSimpleClans.java:58) ~[?:?]
	at net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans.onEnable(DynmapSimpleClans.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-265]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[14:01:08] [Server thread/INFO]: [Dynmap-SimpleClans] Disabling Dynmap-SimpleClans v1.4.0
```

Dynmap error, but it still runs:
```
[14:00:59] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] net/minecraft/server/v1_16_R2/IRegistry initializing dynmap v3.1-beta4-421 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/IRegistry
	at org.dynmap.bukkit.Helper.getHelper(Helper.java:46) ~[?:?]
	at org.dynmap.bukkit.DynmapPlugin.onLoad(DynmapPlugin.java:821) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-265]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-265]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.IRegistry
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.4.jar:git-Paper-265]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-265]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 7 more
```

Full log:
[latest.log](https://github.com/RoinujNosde/Dynmap-SimpleClans/files/5513021/latest.log)

**Comment by Freddo3000** [comment]
I just realized I missed something obvious:
```
[14:01:07] [Server thread/INFO]: [dynmap] Enabling dynmap v3.1-beta4-421*
[14:01:07] [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)
```

**Comment by Freddo3000** [comment]
Updating to dynmap beta 5 resolved the issue.

**Comment by RoinujNosde** [comment]
:+1:
